### ISSUE TITLE
Deuxieme prénom pas reconnu

### ISSUE THREAD

**Issue by PAVaillancourt** [SamuelYvon/NameValidator#2]
Avec comme en-tête de fichier: 
/*
 \* Abc Def Ghi 1234567
*/
le script retourne: Étudiant trouvé: 'Abc Ghi' avec le matricule 1234567.

Expected: Étudiant trouvé: 'Abc Def Ghi' avec le matricule 1234567.

Je metterais un trait-d'union dans mon prénom mais il n'y en a pas dans mon dossier étudiant donc ça risque de poser problème.

**Comment by SamuelYvon** [comment]
Ça devrait être réglé bientôt :)
